// IconName — union of Ionicons icon names used across UI primitives.
// Using `keyof typeof Ionicons.glyphMap` would be ideal but causes
// circular import issues. This manual union covers the icons we use.
export type IconName =
  | 'checkmark-circle'
  | 'close-circle'
  | 'alert-circle'
  | 'information-circle'
  | 'arrow-back'
  | 'chevron-forward'
  | 'chevron-back'
  | 'chevron-down'
  | 'chevron-up'
  | 'add'
  | 'create'
  | 'trash'
  | 'download'
  | 'refresh'
  | 'person'
  | 'people'
  | 'car'
  | 'call'
  | 'mail'
  | 'location'
  | 'time'
  | 'calendar'
  | 'settings'
  | 'log-out'
  | 'eye'
  | 'eye-off'
  | 'search'
  | 'filter'
  | 'list'
  | 'grid'
  | 'notifications'
  | 'shield-checkmark'
  | 'warning'
  | 'checkmark'
  | 'close'
  | 'ellipse'
  | 'pulse'
  | 'navigate'
  | 'construct'
  | 'medical'
  | 'mic'
  | 'volume-high'
  | 'speedometer'
  | 'cube'
  | 'star'
  | 'phone-portrait'
  | 'ribbon'
  | string; // fallback for any Ionicons name
